
# This file is automatically generated, you probably don't want to edit this

corrplotbuilderOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "corrplotbuilderOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            annotationsJson = "",
            chartSnapshot = "",
            clientBundleHash = "",
            corrMethod = "pearson",
            exportPath = "",
            exportRequest = "",
            graphType = "corrheatmap",
            styleLibrary = "",
            styleStamp = FALSE,
            vars = NULL,
            chartSpec = "", ...) {

            super$initialize(
                package="plotstudio",
                name="corrplotbuilder",
                requiresData=TRUE,
                ...)

            private$..annotationsJson <- jmvcore::OptionString$new(
                "annotationsJson",
                annotationsJson,
                default="",
                hidden=TRUE)
            private$..chartSnapshot <- jmvcore::OptionString$new(
                "chartSnapshot",
                chartSnapshot,
                default="",
                hidden=TRUE)
            private$..clientBundleHash <- jmvcore::OptionString$new(
                "clientBundleHash",
                clientBundleHash,
                default="",
                hidden=TRUE)
            private$..corrMethod <- jmvcore::OptionList$new(
                "corrMethod",
                corrMethod,
                hidden=TRUE,
                options=list(
                    "pearson",
                    "spearman",
                    "kendall"),
                default="pearson")
            private$..exportPath <- jmvcore::OptionString$new(
                "exportPath",
                exportPath,
                default="",
                hidden=TRUE)
            private$..exportRequest <- jmvcore::OptionString$new(
                "exportRequest",
                exportRequest,
                default="",
                hidden=TRUE)
            private$..graphType <- jmvcore::OptionList$new(
                "graphType",
                graphType,
                hidden=TRUE,
                options=list(
                    "corrheatmap",
                    "corrcircles",
                    "corrnumbers",
                    "corrmixed"),
                default="corrheatmap")
            private$..styleLibrary <- jmvcore::OptionString$new(
                "styleLibrary",
                styleLibrary,
                default="",
                hidden=TRUE)
            private$..styleStamp <- jmvcore::OptionBool$new(
                "styleStamp",
                styleStamp,
                default=FALSE,
                hidden=TRUE)
            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric"))
            private$..chartSpec <- jmvcore::OptionString$new(
                "chartSpec",
                chartSpec,
                default="",
                hidden=TRUE)

            self$.addOption(private$..annotationsJson)
            self$.addOption(private$..chartSnapshot)
            self$.addOption(private$..clientBundleHash)
            self$.addOption(private$..corrMethod)
            self$.addOption(private$..exportPath)
            self$.addOption(private$..exportRequest)
            self$.addOption(private$..graphType)
            self$.addOption(private$..styleLibrary)
            self$.addOption(private$..styleStamp)
            self$.addOption(private$..vars)
            self$.addOption(private$..chartSpec)
        }),
    active = list(
        annotationsJson = function() private$..annotationsJson$value,
        chartSnapshot = function() private$..chartSnapshot$value,
        clientBundleHash = function() private$..clientBundleHash$value,
        corrMethod = function() private$..corrMethod$value,
        exportPath = function() private$..exportPath$value,
        exportRequest = function() private$..exportRequest$value,
        graphType = function() private$..graphType$value,
        styleLibrary = function() private$..styleLibrary$value,
        styleStamp = function() private$..styleStamp$value,
        vars = function() private$..vars$value,
        chartSpec = function() private$..chartSpec$value),
    private = list(
        ..annotationsJson = NA,
        ..chartSnapshot = NA,
        ..clientBundleHash = NA,
        ..corrMethod = NA,
        ..exportPath = NA,
        ..exportRequest = NA,
        ..graphType = NA,
        ..styleLibrary = NA,
        ..styleStamp = NA,
        ..vars = NA,
        ..chartSpec = NA)
)

corrplotbuilderResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "corrplotbuilderResults",
    inherit = jmvcore::Group,
    active = list(
        widget = function() private$.items[["widget"]],
        exportStatus = function() private$.items[["exportStatus"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Correlation Matrix")
            self$add(jmvcore::Html$new(
                options=options,
                name="widget",
                title="Correlation Matrix",
                visible=TRUE))
            self$add(jmvcore::Html$new(
                options=options,
                name="exportStatus",
                title="Export Status",
                visible=TRUE))}))

corrplotbuilderBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "corrplotbuilderBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "plotstudio",
                name = "corrplotbuilder",
                version = c(0,0,1),
                options = options,
                results = corrplotbuilderResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Correlation Matrix
#'
#' Display the correlations among two or more numeric variables as a matrix, 
#' using a heatmap, circles, numbers, or a mixed layout on a diverging color 
#' scale. Reports r, p, and n for each pair (pairwise complete), with 
#' significance stars, optional matrix-wide p-value adjustment, and control 
#' over the triangle, diagonal, and nonsignificant cells.
#' 
#' @param annotationsJson .
#' @param chartSnapshot .
#' @param clientBundleHash .
#' @param corrMethod .
#' @param data .
#' @param exportPath .
#' @param exportRequest .
#' @param graphType .
#' @param styleLibrary .
#' @param styleStamp .
#' @param vars .
#' @param chartSpec .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$widget} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$exportStatus} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' @export
corrplotbuilder <- function(
    annotationsJson = "",
    chartSnapshot = "",
    clientBundleHash = "",
    corrMethod = "pearson",
    data,
    exportPath = "",
    exportRequest = "",
    graphType = "corrheatmap",
    styleLibrary = "",
    styleStamp = FALSE,
    vars,
    chartSpec = "") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("corrplotbuilder requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))


    options <- corrplotbuilderOptions$new(
        annotationsJson = annotationsJson,
        chartSnapshot = chartSnapshot,
        clientBundleHash = clientBundleHash,
        corrMethod = corrMethod,
        exportPath = exportPath,
        exportRequest = exportRequest,
        graphType = graphType,
        styleLibrary = styleLibrary,
        styleStamp = styleStamp,
        vars = vars,
        chartSpec = chartSpec)

    analysis <- corrplotbuilderClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

