
# This file is automatically generated, you probably don't want to edit this

distplotbuilderOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "distplotbuilderOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            annotationsJson = "",
            chartSnapshot = "",
            clientBundleHash = "",
            errorBarType = "se",
            exportPath = "",
            exportRequest = "",
            facetVar = NULL,
            graphType = "histogram",
            groupVar = NULL,
            histBins = 30,
            histPosition = "overlay",
            histStat = "count",
            paletteLibrary = "",
            showDataPoints = FALSE,
            styleLibrary = "",
            styleStamp = FALSE,
            summaryFunc = "mean",
            var = NULL,
            chartSpec = "", ...) {

            super$initialize(
                package="plotstudio",
                name="distplotbuilder",
                requiresData=TRUE,
                ...)

            private$..annotationsJson <- jmvcore::OptionString$new(
                "annotationsJson",
                annotationsJson,
                default="",
                hidden=TRUE)
            private$..chartSnapshot <- jmvcore::OptionString$new(
                "chartSnapshot",
                chartSnapshot,
                default="",
                hidden=TRUE)
            private$..clientBundleHash <- jmvcore::OptionString$new(
                "clientBundleHash",
                clientBundleHash,
                default="",
                hidden=TRUE)
            private$..errorBarType <- jmvcore::OptionList$new(
                "errorBarType",
                errorBarType,
                options=list(
                    "se",
                    "sd",
                    "ci95",
                    "ci99",
                    "none"),
                default="se",
                hidden=TRUE)
            private$..exportPath <- jmvcore::OptionString$new(
                "exportPath",
                exportPath,
                default="",
                hidden=TRUE)
            private$..exportRequest <- jmvcore::OptionString$new(
                "exportRequest",
                exportRequest,
                default="",
                hidden=TRUE)
            private$..facetVar <- jmvcore::OptionVariable$new(
                "facetVar",
                facetVar,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..graphType <- jmvcore::OptionList$new(
                "graphType",
                graphType,
                hidden=TRUE,
                options=list(
                    "histogram",
                    "density",
                    "histdensity",
                    "box",
                    "violin",
                    "raincloud",
                    "qq",
                    "ecdf"),
                default="histogram")
            private$..groupVar <- jmvcore::OptionVariable$new(
                "groupVar",
                groupVar,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..histBins <- jmvcore::OptionInteger$new(
                "histBins",
                histBins,
                default=30,
                min=1,
                max=500,
                hidden=TRUE)
            private$..histPosition <- jmvcore::OptionList$new(
                "histPosition",
                histPosition,
                options=list(
                    "overlay",
                    "stack",
                    "dodge"),
                default="overlay",
                hidden=TRUE)
            private$..histStat <- jmvcore::OptionList$new(
                "histStat",
                histStat,
                options=list(
                    "count",
                    "density",
                    "proportion"),
                default="count",
                hidden=TRUE)
            private$..paletteLibrary <- jmvcore::OptionString$new(
                "paletteLibrary",
                paletteLibrary,
                default="",
                hidden=TRUE)
            private$..showDataPoints <- jmvcore::OptionBool$new(
                "showDataPoints",
                showDataPoints,
                default=FALSE,
                hidden=TRUE)
            private$..styleLibrary <- jmvcore::OptionString$new(
                "styleLibrary",
                styleLibrary,
                default="",
                hidden=TRUE)
            private$..styleStamp <- jmvcore::OptionBool$new(
                "styleStamp",
                styleStamp,
                default=FALSE,
                hidden=TRUE)
            private$..summaryFunc <- jmvcore::OptionList$new(
                "summaryFunc",
                summaryFunc,
                options=list(
                    "mean",
                    "median"),
                default="mean",
                hidden=TRUE)
            private$..var <- jmvcore::OptionVariable$new(
                "var",
                var,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..chartSpec <- jmvcore::OptionString$new(
                "chartSpec",
                chartSpec,
                default="",
                hidden=TRUE)

            self$.addOption(private$..annotationsJson)
            self$.addOption(private$..chartSnapshot)
            self$.addOption(private$..clientBundleHash)
            self$.addOption(private$..errorBarType)
            self$.addOption(private$..exportPath)
            self$.addOption(private$..exportRequest)
            self$.addOption(private$..facetVar)
            self$.addOption(private$..graphType)
            self$.addOption(private$..groupVar)
            self$.addOption(private$..histBins)
            self$.addOption(private$..histPosition)
            self$.addOption(private$..histStat)
            self$.addOption(private$..paletteLibrary)
            self$.addOption(private$..showDataPoints)
            self$.addOption(private$..styleLibrary)
            self$.addOption(private$..styleStamp)
            self$.addOption(private$..summaryFunc)
            self$.addOption(private$..var)
            self$.addOption(private$..chartSpec)
        }),
    active = list(
        annotationsJson = function() private$..annotationsJson$value,
        chartSnapshot = function() private$..chartSnapshot$value,
        clientBundleHash = function() private$..clientBundleHash$value,
        errorBarType = function() private$..errorBarType$value,
        exportPath = function() private$..exportPath$value,
        exportRequest = function() private$..exportRequest$value,
        facetVar = function() private$..facetVar$value,
        graphType = function() private$..graphType$value,
        groupVar = function() private$..groupVar$value,
        histBins = function() private$..histBins$value,
        histPosition = function() private$..histPosition$value,
        histStat = function() private$..histStat$value,
        paletteLibrary = function() private$..paletteLibrary$value,
        showDataPoints = function() private$..showDataPoints$value,
        styleLibrary = function() private$..styleLibrary$value,
        styleStamp = function() private$..styleStamp$value,
        summaryFunc = function() private$..summaryFunc$value,
        var = function() private$..var$value,
        chartSpec = function() private$..chartSpec$value),
    private = list(
        ..annotationsJson = NA,
        ..chartSnapshot = NA,
        ..clientBundleHash = NA,
        ..errorBarType = NA,
        ..exportPath = NA,
        ..exportRequest = NA,
        ..facetVar = NA,
        ..graphType = NA,
        ..groupVar = NA,
        ..histBins = NA,
        ..histPosition = NA,
        ..histStat = NA,
        ..paletteLibrary = NA,
        ..showDataPoints = NA,
        ..styleLibrary = NA,
        ..styleStamp = NA,
        ..summaryFunc = NA,
        ..var = NA,
        ..chartSpec = NA)
)

distplotbuilderResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "distplotbuilderResults",
    inherit = jmvcore::Group,
    active = list(
        widget = function() private$.items[["widget"]],
        exportStatus = function() private$.items[["exportStatus"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Distribution")
            self$add(jmvcore::Html$new(
                options=options,
                name="widget",
                title="Distribution",
                visible=TRUE))
            self$add(jmvcore::Html$new(
                options=options,
                name="exportStatus",
                title="Export Status",
                visible=TRUE))}))

distplotbuilderBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "distplotbuilderBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "plotstudio",
                name = "distplotbuilder",
                version = c(0,0,1),
                options = options,
                results = distplotbuilderResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Distribution
#'
#' Examine the distribution of a single numeric variable. Draws histograms, 
#' density curves, histogram plus density, box, violin, or raincloud plots, 
#' Q-Q plots with confidence bands, and ECDF curves, with optional 
#' normal-curve overlays, rug marks, and Shapiro-Wilk normality tests. Group 
#' or facet to compare distributions side by side.
#' 
#' @param annotationsJson .
#' @param chartSnapshot .
#' @param clientBundleHash .
#' @param data .
#' @param errorBarType .
#' @param exportPath .
#' @param exportRequest .
#' @param facetVar .
#' @param graphType .
#' @param groupVar .
#' @param histBins .
#' @param histPosition .
#' @param histStat .
#' @param paletteLibrary .
#' @param showDataPoints .
#' @param styleLibrary .
#' @param styleStamp .
#' @param summaryFunc .
#' @param var .
#' @param chartSpec .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$widget} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$exportStatus} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' @export
distplotbuilder <- function(
    annotationsJson = "",
    chartSnapshot = "",
    clientBundleHash = "",
    data,
    errorBarType = "se",
    exportPath = "",
    exportRequest = "",
    facetVar,
    graphType = "histogram",
    groupVar,
    histBins = 30,
    histPosition = "overlay",
    histStat = "count",
    paletteLibrary = "",
    showDataPoints = FALSE,
    styleLibrary = "",
    styleStamp = FALSE,
    summaryFunc = "mean",
    var,
    chartSpec = "") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("distplotbuilder requires jmvcore to be installed (restart may be required)")

    if ( ! missing(facetVar)) facetVar <- jmvcore::resolveQuo(jmvcore::enquo(facetVar))
    if ( ! missing(groupVar)) groupVar <- jmvcore::resolveQuo(jmvcore::enquo(groupVar))
    if ( ! missing(var)) var <- jmvcore::resolveQuo(jmvcore::enquo(var))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(facetVar), facetVar, NULL),
            `if`( ! missing(groupVar), groupVar, NULL),
            `if`( ! missing(var), var, NULL))

    for (v in facetVar) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in groupVar) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- distplotbuilderOptions$new(
        annotationsJson = annotationsJson,
        chartSnapshot = chartSnapshot,
        clientBundleHash = clientBundleHash,
        errorBarType = errorBarType,
        exportPath = exportPath,
        exportRequest = exportRequest,
        facetVar = facetVar,
        graphType = graphType,
        groupVar = groupVar,
        histBins = histBins,
        histPosition = histPosition,
        histStat = histStat,
        paletteLibrary = paletteLibrary,
        showDataPoints = showDataPoints,
        styleLibrary = styleLibrary,
        styleStamp = styleStamp,
        summaryFunc = summaryFunc,
        var = var,
        chartSpec = chartSpec)

    analysis <- distplotbuilderClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

