
# This file is automatically generated, you probably don't want to edit this

helpmechooseOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "helpmechooseOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL, ...) {

            super$initialize(
                package="plotstudio",
                name="helpmechoose",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                default=NULL)

            self$.addOption(private$..vars)
        }),
    active = list(
        vars = function() private$..vars$value),
    private = list(
        ..vars = NA)
)

helpmechooseResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "helpmechooseResults",
    inherit = jmvcore::Group,
    active = list(
        widget = function() private$.items[["widget"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Help Me Choose")
            self$add(jmvcore::Html$new(
                options=options,
                name="widget",
                title="Help Me Choose",
                visible=TRUE))}))

helpmechooseBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "helpmechooseBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "plotstudio",
                name = "helpmechoose",
                version = c(0,0,1),
                options = options,
                results = helpmechooseResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Help Me Choose
#'
#' A question-driven guide, not a chart, that recommends which Plot Studio 
#' analysis and graph type fit your goal, with a plain-language reason for 
#' each. Answer a few questions, or drop in the exact variables you plan to 
#' plot and it classifies them and suggests a best match plus an alternative.
#' 
#' @param data .
#' @param vars .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$widget} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' @export
helpmechoose <- function(
    data,
    vars = NULL) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("helpmechoose requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))


    options <- helpmechooseOptions$new(
        vars = vars)

    analysis <- helpmechooseClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

