
# This file is automatically generated, you probably don't want to edit this

likertplotbuilderOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "likertplotbuilderOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            annotationsJson = "",
            chartSnapshot = "",
            clientBundleHash = "",
            exportPath = "",
            exportRequest = "",
            graphType = "likertdiverging",
            items = NULL,
            likertCiLevel = 0.95,
            styleLibrary = "",
            styleStamp = FALSE,
            chartSpec = "", ...) {

            super$initialize(
                package="plotstudio",
                name="likertplotbuilder",
                requiresData=TRUE,
                ...)

            private$..annotationsJson <- jmvcore::OptionString$new(
                "annotationsJson",
                annotationsJson,
                default="",
                hidden=TRUE)
            private$..chartSnapshot <- jmvcore::OptionString$new(
                "chartSnapshot",
                chartSnapshot,
                default="",
                hidden=TRUE)
            private$..clientBundleHash <- jmvcore::OptionString$new(
                "clientBundleHash",
                clientBundleHash,
                default="",
                hidden=TRUE)
            private$..exportPath <- jmvcore::OptionString$new(
                "exportPath",
                exportPath,
                default="",
                hidden=TRUE)
            private$..exportRequest <- jmvcore::OptionString$new(
                "exportRequest",
                exportRequest,
                default="",
                hidden=TRUE)
            private$..graphType <- jmvcore::OptionList$new(
                "graphType",
                graphType,
                hidden=TRUE,
                options=list(
                    "likertdiverging",
                    "likertstacked",
                    "likertmeans"),
                default="likertdiverging")
            private$..items <- jmvcore::OptionVariables$new(
                "items",
                items,
                suggested=list(
                    "ordinal",
                    "continuous"),
                permitted=list(
                    "factor",
                    "numeric"))
            private$..likertCiLevel <- jmvcore::OptionNumber$new(
                "likertCiLevel",
                likertCiLevel,
                default=0.95,
                min=0.5,
                max=0.999,
                hidden=TRUE)
            private$..styleLibrary <- jmvcore::OptionString$new(
                "styleLibrary",
                styleLibrary,
                default="",
                hidden=TRUE)
            private$..styleStamp <- jmvcore::OptionBool$new(
                "styleStamp",
                styleStamp,
                default=FALSE,
                hidden=TRUE)
            private$..chartSpec <- jmvcore::OptionString$new(
                "chartSpec",
                chartSpec,
                default="",
                hidden=TRUE)

            self$.addOption(private$..annotationsJson)
            self$.addOption(private$..chartSnapshot)
            self$.addOption(private$..clientBundleHash)
            self$.addOption(private$..exportPath)
            self$.addOption(private$..exportRequest)
            self$.addOption(private$..graphType)
            self$.addOption(private$..items)
            self$.addOption(private$..likertCiLevel)
            self$.addOption(private$..styleLibrary)
            self$.addOption(private$..styleStamp)
            self$.addOption(private$..chartSpec)
        }),
    active = list(
        annotationsJson = function() private$..annotationsJson$value,
        chartSnapshot = function() private$..chartSnapshot$value,
        clientBundleHash = function() private$..clientBundleHash$value,
        exportPath = function() private$..exportPath$value,
        exportRequest = function() private$..exportRequest$value,
        graphType = function() private$..graphType$value,
        items = function() private$..items$value,
        likertCiLevel = function() private$..likertCiLevel$value,
        styleLibrary = function() private$..styleLibrary$value,
        styleStamp = function() private$..styleStamp$value,
        chartSpec = function() private$..chartSpec$value),
    private = list(
        ..annotationsJson = NA,
        ..chartSnapshot = NA,
        ..clientBundleHash = NA,
        ..exportPath = NA,
        ..exportRequest = NA,
        ..graphType = NA,
        ..items = NA,
        ..likertCiLevel = NA,
        ..styleLibrary = NA,
        ..styleStamp = NA,
        ..chartSpec = NA)
)

likertplotbuilderResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "likertplotbuilderResults",
    inherit = jmvcore::Group,
    active = list(
        widget = function() private$.items[["widget"]],
        snapshotImage = function() private$.items[["snapshotImage"]],
        exportStatus = function() private$.items[["exportStatus"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Likert / Survey")
            self$add(jmvcore::Html$new(
                options=options,
                name="widget",
                title="Likert / Survey",
                visible=TRUE))
            self$add(jmvcore::Image$new(
                options=options,
                name="snapshotImage",
                title="Chart (static copy)",
                width=700,
                height=450,
                renderFun=".renderSnapshot",
                visible=FALSE))
            self$add(jmvcore::Html$new(
                options=options,
                name="exportStatus",
                title="Export Status",
                visible=TRUE))}))

likertplotbuilderBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "likertplotbuilderBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "plotstudio",
                name = "likertplotbuilder",
                version = c(0,0,1),
                options = options,
                results = likertplotbuilderResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Likert / Survey
#'
#' Visualize a battery of rating-scale (Likert) items that share one response 
#' scale. Draws diverging stacked bars centered on the neutral category, 100\% 
#' stacked bars, or item means with confidence intervals, with net-agreement 
#' sorting, reverse-scoring for negatively worded items, and Cronbach's alpha. 
#' Drag rows to reorder the questions.
#' 
#' @param annotationsJson .
#' @param chartSnapshot .
#' @param clientBundleHash .
#' @param data .
#' @param exportPath .
#' @param exportRequest .
#' @param graphType .
#' @param items .
#' @param likertCiLevel .
#' @param styleLibrary .
#' @param styleStamp .
#' @param chartSpec .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$widget} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$snapshotImage} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$exportStatus} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' @export
likertplotbuilder <- function(
    annotationsJson = "",
    chartSnapshot = "",
    clientBundleHash = "",
    data,
    exportPath = "",
    exportRequest = "",
    graphType = "likertdiverging",
    items,
    likertCiLevel = 0.95,
    styleLibrary = "",
    styleStamp = FALSE,
    chartSpec = "") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("likertplotbuilder requires jmvcore to be installed (restart may be required)")

    if ( ! missing(items)) items <- jmvcore::resolveQuo(jmvcore::enquo(items))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(items), items, NULL))


    options <- likertplotbuilderOptions$new(
        annotationsJson = annotationsJson,
        chartSnapshot = chartSnapshot,
        clientBundleHash = clientBundleHash,
        exportPath = exportPath,
        exportRequest = exportRequest,
        graphType = graphType,
        items = items,
        likertCiLevel = likertCiLevel,
        styleLibrary = styleLibrary,
        styleStamp = styleStamp,
        chartSpec = chartSpec)

    analysis <- likertplotbuilderClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

