
# This file is automatically generated, you probably don't want to edit this

plotbuilderOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "plotbuilderOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            xvar = NULL,
            yvar = NULL,
            groupVar = NULL,
            facetVar = NULL,
            graphType = "bar",
            summaryFunc = "mean",
            errorBarType = "se",
            showDataPoints = FALSE,
            exportRequest = "",
            exportPath = "",
            chartSnapshot = "",
            clientBundleHash = "",
            paletteLibrary = "",
            styleLibrary = "",
            styleStamp = FALSE,
            annotationsJson = "",
            chartSpec = "", ...) {

            super$initialize(
                package="plotstudio",
                name="plotbuilder",
                requiresData=TRUE,
                ...)

            private$..xvar <- jmvcore::OptionVariable$new(
                "xvar",
                xvar,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..yvar <- jmvcore::OptionVariable$new(
                "yvar",
                yvar,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..groupVar <- jmvcore::OptionVariable$new(
                "groupVar",
                groupVar,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..facetVar <- jmvcore::OptionVariable$new(
                "facetVar",
                facetVar,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..graphType <- jmvcore::OptionList$new(
                "graphType",
                graphType,
                hidden=TRUE,
                options=list(
                    "bar",
                    "line",
                    "dot",
                    "box",
                    "violin",
                    "raincloud"),
                default="bar")
            private$..summaryFunc <- jmvcore::OptionList$new(
                "summaryFunc",
                summaryFunc,
                hidden=TRUE,
                options=list(
                    "mean",
                    "median"),
                default="mean")
            private$..errorBarType <- jmvcore::OptionList$new(
                "errorBarType",
                errorBarType,
                hidden=TRUE,
                options=list(
                    "se",
                    "sd",
                    "ci95",
                    "ci99",
                    "none"),
                default="se")
            private$..showDataPoints <- jmvcore::OptionBool$new(
                "showDataPoints",
                showDataPoints,
                default=FALSE,
                hidden=TRUE)
            private$..exportRequest <- jmvcore::OptionString$new(
                "exportRequest",
                exportRequest,
                default="",
                hidden=TRUE)
            private$..exportPath <- jmvcore::OptionString$new(
                "exportPath",
                exportPath,
                default="",
                hidden=TRUE)
            private$..chartSnapshot <- jmvcore::OptionString$new(
                "chartSnapshot",
                chartSnapshot,
                default="",
                hidden=TRUE)
            private$..clientBundleHash <- jmvcore::OptionString$new(
                "clientBundleHash",
                clientBundleHash,
                default="",
                hidden=TRUE)
            private$..paletteLibrary <- jmvcore::OptionString$new(
                "paletteLibrary",
                paletteLibrary,
                default="",
                hidden=TRUE)
            private$..styleLibrary <- jmvcore::OptionString$new(
                "styleLibrary",
                styleLibrary,
                default="",
                hidden=TRUE)
            private$..styleStamp <- jmvcore::OptionBool$new(
                "styleStamp",
                styleStamp,
                default=FALSE,
                hidden=TRUE)
            private$..annotationsJson <- jmvcore::OptionString$new(
                "annotationsJson",
                annotationsJson,
                default="",
                hidden=TRUE)
            private$..chartSpec <- jmvcore::OptionString$new(
                "chartSpec",
                chartSpec,
                default="",
                hidden=TRUE)

            self$.addOption(private$..xvar)
            self$.addOption(private$..yvar)
            self$.addOption(private$..groupVar)
            self$.addOption(private$..facetVar)
            self$.addOption(private$..graphType)
            self$.addOption(private$..summaryFunc)
            self$.addOption(private$..errorBarType)
            self$.addOption(private$..showDataPoints)
            self$.addOption(private$..exportRequest)
            self$.addOption(private$..exportPath)
            self$.addOption(private$..chartSnapshot)
            self$.addOption(private$..clientBundleHash)
            self$.addOption(private$..paletteLibrary)
            self$.addOption(private$..styleLibrary)
            self$.addOption(private$..styleStamp)
            self$.addOption(private$..annotationsJson)
            self$.addOption(private$..chartSpec)
        }),
    active = list(
        xvar = function() private$..xvar$value,
        yvar = function() private$..yvar$value,
        groupVar = function() private$..groupVar$value,
        facetVar = function() private$..facetVar$value,
        graphType = function() private$..graphType$value,
        summaryFunc = function() private$..summaryFunc$value,
        errorBarType = function() private$..errorBarType$value,
        showDataPoints = function() private$..showDataPoints$value,
        exportRequest = function() private$..exportRequest$value,
        exportPath = function() private$..exportPath$value,
        chartSnapshot = function() private$..chartSnapshot$value,
        clientBundleHash = function() private$..clientBundleHash$value,
        paletteLibrary = function() private$..paletteLibrary$value,
        styleLibrary = function() private$..styleLibrary$value,
        styleStamp = function() private$..styleStamp$value,
        annotationsJson = function() private$..annotationsJson$value,
        chartSpec = function() private$..chartSpec$value),
    private = list(
        ..xvar = NA,
        ..yvar = NA,
        ..groupVar = NA,
        ..facetVar = NA,
        ..graphType = NA,
        ..summaryFunc = NA,
        ..errorBarType = NA,
        ..showDataPoints = NA,
        ..exportRequest = NA,
        ..exportPath = NA,
        ..chartSnapshot = NA,
        ..clientBundleHash = NA,
        ..paletteLibrary = NA,
        ..styleLibrary = NA,
        ..styleStamp = NA,
        ..annotationsJson = NA,
        ..chartSpec = NA)
)

plotbuilderResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "plotbuilderResults",
    inherit = jmvcore::Group,
    active = list(
        widget = function() private$.items[["widget"]],
        exportStatus = function() private$.items[["exportStatus"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Compare Groups")
            self$add(jmvcore::Html$new(
                options=options,
                name="widget",
                title="Compare Groups",
                visible=TRUE))
            self$add(jmvcore::Html$new(
                options=options,
                name="exportStatus",
                title="Export Status",
                visible=TRUE))}))

plotbuilderBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "plotbuilderBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "plotstudio",
                name = "plotbuilder",
                version = c(0,0,1),
                options = options,
                results = plotbuilderResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Compare Groups
#'
#' Compare a numeric outcome across the levels of a categorical variable. 
#' Draws bar, line, dot, box, violin, or raincloud charts with mean or median 
#' summaries and SE, SD, or confidence-interval error bars, plus optional 
#' significance brackets. Add a second factor for grouped colors and a facet 
#' variable for panels, then click any part of the chart to style it.
#' 
#' @param data .
#' @param xvar .
#' @param yvar .
#' @param groupVar .
#' @param facetVar .
#' @param graphType .
#' @param summaryFunc .
#' @param errorBarType .
#' @param showDataPoints .
#' @param exportRequest .
#' @param exportPath .
#' @param chartSnapshot .
#' @param clientBundleHash .
#' @param paletteLibrary .
#' @param styleLibrary .
#' @param styleStamp .
#' @param annotationsJson .
#' @param chartSpec .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$widget} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$exportStatus} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' @export
plotbuilder <- function(
    data,
    xvar,
    yvar,
    groupVar,
    facetVar,
    graphType = "bar",
    summaryFunc = "mean",
    errorBarType = "se",
    showDataPoints = FALSE,
    exportRequest = "",
    exportPath = "",
    chartSnapshot = "",
    clientBundleHash = "",
    paletteLibrary = "",
    styleLibrary = "",
    styleStamp = FALSE,
    annotationsJson = "",
    chartSpec = "") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("plotbuilder requires jmvcore to be installed (restart may be required)")

    if ( ! missing(xvar)) xvar <- jmvcore::resolveQuo(jmvcore::enquo(xvar))
    if ( ! missing(yvar)) yvar <- jmvcore::resolveQuo(jmvcore::enquo(yvar))
    if ( ! missing(groupVar)) groupVar <- jmvcore::resolveQuo(jmvcore::enquo(groupVar))
    if ( ! missing(facetVar)) facetVar <- jmvcore::resolveQuo(jmvcore::enquo(facetVar))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(xvar), xvar, NULL),
            `if`( ! missing(yvar), yvar, NULL),
            `if`( ! missing(groupVar), groupVar, NULL),
            `if`( ! missing(facetVar), facetVar, NULL))

    for (v in xvar) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in groupVar) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in facetVar) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- plotbuilderOptions$new(
        xvar = xvar,
        yvar = yvar,
        groupVar = groupVar,
        facetVar = facetVar,
        graphType = graphType,
        summaryFunc = summaryFunc,
        errorBarType = errorBarType,
        showDataPoints = showDataPoints,
        exportRequest = exportRequest,
        exportPath = exportPath,
        chartSnapshot = chartSnapshot,
        clientBundleHash = clientBundleHash,
        paletteLibrary = paletteLibrary,
        styleLibrary = styleLibrary,
        styleStamp = styleStamp,
        annotationsJson = annotationsJson,
        chartSpec = chartSpec)

    analysis <- plotbuilderClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

