
# This file is automatically generated, you probably don't want to edit this

rmplotbuilderOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "rmplotbuilderOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            annotationsJson = "",
            betweenVar = NULL,
            bs = NULL,
            chartSnapshot = "",
            clientBundleHash = "",
            connectSubjects = FALSE,
            displayRoles = "",
            errorBarMethod = "within",
            errorBarType = "se",
            exportPath = "",
            exportRequest = "",
            graphType = "line",
            measures = NULL,
            paletteLibrary = "",
            rm = NULL,
            rmCells = NULL,
            showDataPoints = FALSE,
            styleLibrary = "",
            styleStamp = FALSE,
            summaryFunc = "mean",
            chartSpec = "", ...) {

            super$initialize(
                package="plotstudio",
                name="rmplotbuilder",
                requiresData=TRUE,
                ...)

            private$..annotationsJson <- jmvcore::OptionString$new(
                "annotationsJson",
                annotationsJson,
                default="",
                hidden=TRUE)
            private$..betweenVar <- jmvcore::OptionVariable$new(
                "betweenVar",
                betweenVar,
                hidden=TRUE,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..bs <- jmvcore::OptionVariables$new(
                "bs",
                bs,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..chartSnapshot <- jmvcore::OptionString$new(
                "chartSnapshot",
                chartSnapshot,
                default="",
                hidden=TRUE)
            private$..clientBundleHash <- jmvcore::OptionString$new(
                "clientBundleHash",
                clientBundleHash,
                default="",
                hidden=TRUE)
            private$..connectSubjects <- jmvcore::OptionBool$new(
                "connectSubjects",
                connectSubjects,
                default=FALSE,
                hidden=TRUE)
            private$..displayRoles <- jmvcore::OptionString$new(
                "displayRoles",
                displayRoles,
                default="",
                hidden=TRUE)
            private$..errorBarMethod <- jmvcore::OptionList$new(
                "errorBarMethod",
                errorBarMethod,
                hidden=TRUE,
                options=list(
                    "within",
                    "between"),
                default="within")
            private$..errorBarType <- jmvcore::OptionList$new(
                "errorBarType",
                errorBarType,
                hidden=TRUE,
                options=list(
                    "se",
                    "sd",
                    "ci95",
                    "ci99",
                    "none"),
                default="se")
            private$..exportPath <- jmvcore::OptionString$new(
                "exportPath",
                exportPath,
                default="",
                hidden=TRUE)
            private$..exportRequest <- jmvcore::OptionString$new(
                "exportRequest",
                exportRequest,
                default="",
                hidden=TRUE)
            private$..graphType <- jmvcore::OptionList$new(
                "graphType",
                graphType,
                hidden=TRUE,
                options=list(
                    "bar",
                    "line",
                    "dot",
                    "box",
                    "violin",
                    "raincloud"),
                default="line")
            private$..measures <- jmvcore::OptionVariables$new(
                "measures",
                measures,
                hidden=TRUE,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..paletteLibrary <- jmvcore::OptionString$new(
                "paletteLibrary",
                paletteLibrary,
                default="",
                hidden=TRUE)
            private$..rm <- jmvcore::OptionArray$new(
                "rm",
                rm,
                default=NULL,
                template=jmvcore::OptionGroup$new(
                    "rm",
                    NULL,
                    elements=list(
                        jmvcore::OptionString$new(
                            "label",
                            NULL),
                        jmvcore::OptionArray$new(
                            "levels",
                            NULL,
                            template=jmvcore::OptionString$new(
                                "levels",
                                NULL)))))
            private$..rmCells <- jmvcore::OptionArray$new(
                "rmCells",
                rmCells,
                default=NULL,
                template=jmvcore::OptionGroup$new(
                    "rmCells",
                    NULL,
                    elements=list(
                        jmvcore::OptionVariable$new(
                            "measure",
                            NULL),
                        jmvcore::OptionArray$new(
                            "cell",
                            NULL,
                            template=jmvcore::OptionString$new(
                                "cell",
                                NULL)))))
            private$..showDataPoints <- jmvcore::OptionBool$new(
                "showDataPoints",
                showDataPoints,
                default=FALSE,
                hidden=TRUE)
            private$..styleLibrary <- jmvcore::OptionString$new(
                "styleLibrary",
                styleLibrary,
                default="",
                hidden=TRUE)
            private$..styleStamp <- jmvcore::OptionBool$new(
                "styleStamp",
                styleStamp,
                default=FALSE,
                hidden=TRUE)
            private$..summaryFunc <- jmvcore::OptionList$new(
                "summaryFunc",
                summaryFunc,
                hidden=TRUE,
                options=list(
                    "mean",
                    "median"),
                default="mean")
            private$..chartSpec <- jmvcore::OptionString$new(
                "chartSpec",
                chartSpec,
                default="",
                hidden=TRUE)

            self$.addOption(private$..annotationsJson)
            self$.addOption(private$..betweenVar)
            self$.addOption(private$..bs)
            self$.addOption(private$..chartSnapshot)
            self$.addOption(private$..clientBundleHash)
            self$.addOption(private$..connectSubjects)
            self$.addOption(private$..displayRoles)
            self$.addOption(private$..errorBarMethod)
            self$.addOption(private$..errorBarType)
            self$.addOption(private$..exportPath)
            self$.addOption(private$..exportRequest)
            self$.addOption(private$..graphType)
            self$.addOption(private$..measures)
            self$.addOption(private$..paletteLibrary)
            self$.addOption(private$..rm)
            self$.addOption(private$..rmCells)
            self$.addOption(private$..showDataPoints)
            self$.addOption(private$..styleLibrary)
            self$.addOption(private$..styleStamp)
            self$.addOption(private$..summaryFunc)
            self$.addOption(private$..chartSpec)
        }),
    active = list(
        annotationsJson = function() private$..annotationsJson$value,
        betweenVar = function() private$..betweenVar$value,
        bs = function() private$..bs$value,
        chartSnapshot = function() private$..chartSnapshot$value,
        clientBundleHash = function() private$..clientBundleHash$value,
        connectSubjects = function() private$..connectSubjects$value,
        displayRoles = function() private$..displayRoles$value,
        errorBarMethod = function() private$..errorBarMethod$value,
        errorBarType = function() private$..errorBarType$value,
        exportPath = function() private$..exportPath$value,
        exportRequest = function() private$..exportRequest$value,
        graphType = function() private$..graphType$value,
        measures = function() private$..measures$value,
        paletteLibrary = function() private$..paletteLibrary$value,
        rm = function() private$..rm$value,
        rmCells = function() private$..rmCells$value,
        showDataPoints = function() private$..showDataPoints$value,
        styleLibrary = function() private$..styleLibrary$value,
        styleStamp = function() private$..styleStamp$value,
        summaryFunc = function() private$..summaryFunc$value,
        chartSpec = function() private$..chartSpec$value),
    private = list(
        ..annotationsJson = NA,
        ..betweenVar = NA,
        ..bs = NA,
        ..chartSnapshot = NA,
        ..clientBundleHash = NA,
        ..connectSubjects = NA,
        ..displayRoles = NA,
        ..errorBarMethod = NA,
        ..errorBarType = NA,
        ..exportPath = NA,
        ..exportRequest = NA,
        ..graphType = NA,
        ..measures = NA,
        ..paletteLibrary = NA,
        ..rm = NA,
        ..rmCells = NA,
        ..showDataPoints = NA,
        ..styleLibrary = NA,
        ..styleStamp = NA,
        ..summaryFunc = NA,
        ..chartSpec = NA)
)

rmplotbuilderResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "rmplotbuilderResults",
    inherit = jmvcore::Group,
    active = list(
        widget = function() private$.items[["widget"]],
        exportStatus = function() private$.items[["exportStatus"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Repeated Measures")
            self$add(jmvcore::Html$new(
                options=options,
                name="widget",
                title="Repeated Measures",
                visible=TRUE))
            self$add(jmvcore::Html$new(
                options=options,
                name="exportStatus",
                title="Export Status",
                visible=TRUE))}))

rmplotbuilderBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "rmplotbuilderBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "plotstudio",
                name = "rmplotbuilder",
                version = c(0,0,1),
                options = options,
                results = rmplotbuilderResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Repeated Measures
#'
#' Plot a within-subjects (repeated measures) outcome recorded on the same 
#' people across two or more occasions, supplied as separate columns in wide 
#' format. Draws line, bar, dot, box, violin, or raincloud charts with 
#' Cousineau-Morey within-subject error bars, optional per-subject lines and 
#' points, paired comparisons, and supported repeated-measures or mixed 
#' (split-plot) omnibus tests. Optional between-subject factors can group or 
#' panel the design.
#' 
#' @param annotationsJson .
#' @param betweenVar .
#' @param bs .
#' @param chartSnapshot .
#' @param clientBundleHash .
#' @param connectSubjects .
#' @param data .
#' @param displayRoles .
#' @param errorBarMethod .
#' @param errorBarType .
#' @param exportPath .
#' @param exportRequest .
#' @param graphType .
#' @param measures .
#' @param paletteLibrary .
#' @param rm .
#' @param rmCells .
#' @param showDataPoints .
#' @param styleLibrary .
#' @param styleStamp .
#' @param summaryFunc .
#' @param chartSpec .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$widget} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$exportStatus} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' @export
rmplotbuilder <- function(
    annotationsJson = "",
    betweenVar,
    bs,
    chartSnapshot = "",
    clientBundleHash = "",
    connectSubjects = FALSE,
    data,
    displayRoles = "",
    errorBarMethod = "within",
    errorBarType = "se",
    exportPath = "",
    exportRequest = "",
    graphType = "line",
    measures,
    paletteLibrary = "",
    rm = NULL,
    rmCells = NULL,
    showDataPoints = FALSE,
    styleLibrary = "",
    styleStamp = FALSE,
    summaryFunc = "mean",
    chartSpec = "") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("rmplotbuilder requires jmvcore to be installed (restart may be required)")

    if ( ! missing(betweenVar)) betweenVar <- jmvcore::resolveQuo(jmvcore::enquo(betweenVar))
    if ( ! missing(bs)) bs <- jmvcore::resolveQuo(jmvcore::enquo(bs))
    if ( ! missing(measures)) measures <- jmvcore::resolveQuo(jmvcore::enquo(measures))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(betweenVar), betweenVar, NULL),
            `if`( ! missing(bs), bs, NULL),
            `if`( ! missing(measures), measures, NULL))

    for (v in betweenVar) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in bs) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- rmplotbuilderOptions$new(
        annotationsJson = annotationsJson,
        betweenVar = betweenVar,
        bs = bs,
        chartSnapshot = chartSnapshot,
        clientBundleHash = clientBundleHash,
        connectSubjects = connectSubjects,
        displayRoles = displayRoles,
        errorBarMethod = errorBarMethod,
        errorBarType = errorBarType,
        exportPath = exportPath,
        exportRequest = exportRequest,
        graphType = graphType,
        measures = measures,
        paletteLibrary = paletteLibrary,
        rm = rm,
        rmCells = rmCells,
        showDataPoints = showDataPoints,
        styleLibrary = styleLibrary,
        styleStamp = styleStamp,
        summaryFunc = summaryFunc,
        chartSpec = chartSpec)

    analysis <- rmplotbuilderClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

