
# This file is automatically generated, you probably don't want to edit this

xyplotbuilderOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "xyplotbuilderOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            annotationsJson = "",
            chartSnapshot = "",
            clientBundleHash = "",
            errorBarType = "se",
            exportPath = "",
            exportRequest = "",
            facetVar = NULL,
            graphType = "scatter",
            groupVar = NULL,
            labelVar = NULL,
            paletteLibrary = "",
            showDataPoints = FALSE,
            sizeVar = NULL,
            styleLibrary = "",
            styleStamp = FALSE,
            summaryFunc = "mean",
            xvar = NULL,
            xyBin = "none",
            xyBinCount = 30,
            xyCILevel = 0.95,
            xyDensity2DLevels = 5,
            xyEllipseLevel = 0.95,
            xyFitType = "linear",
            xyLoessSpan = 0.75,
            xyMarginal = "none",
            xyMarginalBins = 30,
            xyShowDensity2D = FALSE,
            xyStatsCorrType = "pearson",
            yvar = NULL,
            chartSpec = "", ...) {

            super$initialize(
                package="plotstudio",
                name="xyplotbuilder",
                requiresData=TRUE,
                ...)

            private$..annotationsJson <- jmvcore::OptionString$new(
                "annotationsJson",
                annotationsJson,
                default="",
                hidden=TRUE)
            private$..chartSnapshot <- jmvcore::OptionString$new(
                "chartSnapshot",
                chartSnapshot,
                default="",
                hidden=TRUE)
            private$..clientBundleHash <- jmvcore::OptionString$new(
                "clientBundleHash",
                clientBundleHash,
                default="",
                hidden=TRUE)
            private$..errorBarType <- jmvcore::OptionList$new(
                "errorBarType",
                errorBarType,
                options=list(
                    "se",
                    "sd",
                    "ci95",
                    "ci99",
                    "none"),
                default="se",
                hidden=TRUE)
            private$..exportPath <- jmvcore::OptionString$new(
                "exportPath",
                exportPath,
                default="",
                hidden=TRUE)
            private$..exportRequest <- jmvcore::OptionString$new(
                "exportRequest",
                exportRequest,
                default="",
                hidden=TRUE)
            private$..facetVar <- jmvcore::OptionVariable$new(
                "facetVar",
                facetVar,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..graphType <- jmvcore::OptionList$new(
                "graphType",
                graphType,
                options=list(
                    "scatter"),
                default="scatter",
                hidden=TRUE)
            private$..groupVar <- jmvcore::OptionVariable$new(
                "groupVar",
                groupVar,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..labelVar <- jmvcore::OptionVariable$new(
                "labelVar",
                labelVar,
                hidden=TRUE)
            private$..paletteLibrary <- jmvcore::OptionString$new(
                "paletteLibrary",
                paletteLibrary,
                default="",
                hidden=TRUE)
            private$..showDataPoints <- jmvcore::OptionBool$new(
                "showDataPoints",
                showDataPoints,
                default=FALSE,
                hidden=TRUE)
            private$..sizeVar <- jmvcore::OptionVariable$new(
                "sizeVar",
                sizeVar,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                hidden=TRUE)
            private$..styleLibrary <- jmvcore::OptionString$new(
                "styleLibrary",
                styleLibrary,
                default="",
                hidden=TRUE)
            private$..styleStamp <- jmvcore::OptionBool$new(
                "styleStamp",
                styleStamp,
                default=FALSE,
                hidden=TRUE)
            private$..summaryFunc <- jmvcore::OptionList$new(
                "summaryFunc",
                summaryFunc,
                options=list(
                    "mean",
                    "median"),
                default="mean",
                hidden=TRUE)
            private$..xvar <- jmvcore::OptionVariable$new(
                "xvar",
                xvar,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric",
                    "factor"))
            private$..xyBin <- jmvcore::OptionList$new(
                "xyBin",
                xyBin,
                hidden=TRUE,
                options=list(
                    "none",
                    "square"),
                default="none")
            private$..xyBinCount <- jmvcore::OptionNumber$new(
                "xyBinCount",
                xyBinCount,
                default=30,
                min=2,
                max=200,
                hidden=TRUE)
            private$..xyCILevel <- jmvcore::OptionNumber$new(
                "xyCILevel",
                xyCILevel,
                default=0.95,
                min=0.5,
                max=0.999,
                hidden=TRUE)
            private$..xyDensity2DLevels <- jmvcore::OptionNumber$new(
                "xyDensity2DLevels",
                xyDensity2DLevels,
                default=5,
                min=1,
                max=12,
                hidden=TRUE)
            private$..xyEllipseLevel <- jmvcore::OptionNumber$new(
                "xyEllipseLevel",
                xyEllipseLevel,
                default=0.95,
                min=0.5,
                max=0.999,
                hidden=TRUE)
            private$..xyFitType <- jmvcore::OptionList$new(
                "xyFitType",
                xyFitType,
                options=list(
                    "linear",
                    "poly2",
                    "poly3",
                    "loess"),
                default="linear",
                hidden=TRUE)
            private$..xyLoessSpan <- jmvcore::OptionNumber$new(
                "xyLoessSpan",
                xyLoessSpan,
                default=0.75,
                min=0.1,
                max=1.5,
                hidden=TRUE)
            private$..xyMarginal <- jmvcore::OptionList$new(
                "xyMarginal",
                xyMarginal,
                hidden=TRUE,
                options=list(
                    "none",
                    "histogram",
                    "density"),
                default="none")
            private$..xyMarginalBins <- jmvcore::OptionNumber$new(
                "xyMarginalBins",
                xyMarginalBins,
                default=30,
                min=5,
                max=100,
                hidden=TRUE)
            private$..xyShowDensity2D <- jmvcore::OptionBool$new(
                "xyShowDensity2D",
                xyShowDensity2D,
                default=FALSE,
                hidden=TRUE)
            private$..xyStatsCorrType <- jmvcore::OptionList$new(
                "xyStatsCorrType",
                xyStatsCorrType,
                options=list(
                    "pearson",
                    "spearman",
                    "kendall"),
                default="pearson",
                hidden=TRUE)
            private$..yvar <- jmvcore::OptionVariable$new(
                "yvar",
                yvar,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric",
                    "factor"))
            private$..chartSpec <- jmvcore::OptionString$new(
                "chartSpec",
                chartSpec,
                default="",
                hidden=TRUE)

            self$.addOption(private$..annotationsJson)
            self$.addOption(private$..chartSnapshot)
            self$.addOption(private$..clientBundleHash)
            self$.addOption(private$..errorBarType)
            self$.addOption(private$..exportPath)
            self$.addOption(private$..exportRequest)
            self$.addOption(private$..facetVar)
            self$.addOption(private$..graphType)
            self$.addOption(private$..groupVar)
            self$.addOption(private$..labelVar)
            self$.addOption(private$..paletteLibrary)
            self$.addOption(private$..showDataPoints)
            self$.addOption(private$..sizeVar)
            self$.addOption(private$..styleLibrary)
            self$.addOption(private$..styleStamp)
            self$.addOption(private$..summaryFunc)
            self$.addOption(private$..xvar)
            self$.addOption(private$..xyBin)
            self$.addOption(private$..xyBinCount)
            self$.addOption(private$..xyCILevel)
            self$.addOption(private$..xyDensity2DLevels)
            self$.addOption(private$..xyEllipseLevel)
            self$.addOption(private$..xyFitType)
            self$.addOption(private$..xyLoessSpan)
            self$.addOption(private$..xyMarginal)
            self$.addOption(private$..xyMarginalBins)
            self$.addOption(private$..xyShowDensity2D)
            self$.addOption(private$..xyStatsCorrType)
            self$.addOption(private$..yvar)
            self$.addOption(private$..chartSpec)
        }),
    active = list(
        annotationsJson = function() private$..annotationsJson$value,
        chartSnapshot = function() private$..chartSnapshot$value,
        clientBundleHash = function() private$..clientBundleHash$value,
        errorBarType = function() private$..errorBarType$value,
        exportPath = function() private$..exportPath$value,
        exportRequest = function() private$..exportRequest$value,
        facetVar = function() private$..facetVar$value,
        graphType = function() private$..graphType$value,
        groupVar = function() private$..groupVar$value,
        labelVar = function() private$..labelVar$value,
        paletteLibrary = function() private$..paletteLibrary$value,
        showDataPoints = function() private$..showDataPoints$value,
        sizeVar = function() private$..sizeVar$value,
        styleLibrary = function() private$..styleLibrary$value,
        styleStamp = function() private$..styleStamp$value,
        summaryFunc = function() private$..summaryFunc$value,
        xvar = function() private$..xvar$value,
        xyBin = function() private$..xyBin$value,
        xyBinCount = function() private$..xyBinCount$value,
        xyCILevel = function() private$..xyCILevel$value,
        xyDensity2DLevels = function() private$..xyDensity2DLevels$value,
        xyEllipseLevel = function() private$..xyEllipseLevel$value,
        xyFitType = function() private$..xyFitType$value,
        xyLoessSpan = function() private$..xyLoessSpan$value,
        xyMarginal = function() private$..xyMarginal$value,
        xyMarginalBins = function() private$..xyMarginalBins$value,
        xyShowDensity2D = function() private$..xyShowDensity2D$value,
        xyStatsCorrType = function() private$..xyStatsCorrType$value,
        yvar = function() private$..yvar$value,
        chartSpec = function() private$..chartSpec$value),
    private = list(
        ..annotationsJson = NA,
        ..chartSnapshot = NA,
        ..clientBundleHash = NA,
        ..errorBarType = NA,
        ..exportPath = NA,
        ..exportRequest = NA,
        ..facetVar = NA,
        ..graphType = NA,
        ..groupVar = NA,
        ..labelVar = NA,
        ..paletteLibrary = NA,
        ..showDataPoints = NA,
        ..sizeVar = NA,
        ..styleLibrary = NA,
        ..styleStamp = NA,
        ..summaryFunc = NA,
        ..xvar = NA,
        ..xyBin = NA,
        ..xyBinCount = NA,
        ..xyCILevel = NA,
        ..xyDensity2DLevels = NA,
        ..xyEllipseLevel = NA,
        ..xyFitType = NA,
        ..xyLoessSpan = NA,
        ..xyMarginal = NA,
        ..xyMarginalBins = NA,
        ..xyShowDensity2D = NA,
        ..xyStatsCorrType = NA,
        ..yvar = NA,
        ..chartSpec = NA)
)

xyplotbuilderResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "xyplotbuilderResults",
    inherit = jmvcore::Group,
    active = list(
        widget = function() private$.items[["widget"]],
        exportStatus = function() private$.items[["exportStatus"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Scatter")
            self$add(jmvcore::Html$new(
                options=options,
                name="widget",
                title="Scatter",
                visible=TRUE))
            self$add(jmvcore::Html$new(
                options=options,
                name="exportStatus",
                title="Export Status",
                visible=TRUE))}))

xyplotbuilderBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "xyplotbuilderBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "plotstudio",
                name = "xyplotbuilder",
                version = c(0,0,1),
                options = options,
                results = xyplotbuilderResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Scatter
#'
#' Show the relationship between two continuous variables as a scatter plot, 
#' with optional linear, polynomial, or LOESS fit lines and confidence bands, 
#' data ellipses, marginal distributions, and Pearson, Spearman, or Kendall 
#' correlation statistics. Color by a grouping variable, add panels, or switch 
#' to a binned tile heatmap for dense data.
#' 
#' @param annotationsJson .
#' @param chartSnapshot .
#' @param clientBundleHash .
#' @param data .
#' @param errorBarType .
#' @param exportPath .
#' @param exportRequest .
#' @param facetVar .
#' @param graphType .
#' @param groupVar .
#' @param labelVar .
#' @param paletteLibrary .
#' @param showDataPoints .
#' @param sizeVar .
#' @param styleLibrary .
#' @param styleStamp .
#' @param summaryFunc .
#' @param xvar .
#' @param xyBin .
#' @param xyBinCount .
#' @param xyCILevel .
#' @param xyDensity2DLevels .
#' @param xyEllipseLevel .
#' @param xyFitType .
#' @param xyLoessSpan .
#' @param xyMarginal .
#' @param xyMarginalBins .
#' @param xyShowDensity2D .
#' @param xyStatsCorrType .
#' @param yvar .
#' @param chartSpec .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$widget} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$exportStatus} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' @export
xyplotbuilder <- function(
    annotationsJson = "",
    chartSnapshot = "",
    clientBundleHash = "",
    data,
    errorBarType = "se",
    exportPath = "",
    exportRequest = "",
    facetVar,
    graphType = "scatter",
    groupVar,
    labelVar,
    paletteLibrary = "",
    showDataPoints = FALSE,
    sizeVar,
    styleLibrary = "",
    styleStamp = FALSE,
    summaryFunc = "mean",
    xvar,
    xyBin = "none",
    xyBinCount = 30,
    xyCILevel = 0.95,
    xyDensity2DLevels = 5,
    xyEllipseLevel = 0.95,
    xyFitType = "linear",
    xyLoessSpan = 0.75,
    xyMarginal = "none",
    xyMarginalBins = 30,
    xyShowDensity2D = FALSE,
    xyStatsCorrType = "pearson",
    yvar,
    chartSpec = "") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("xyplotbuilder requires jmvcore to be installed (restart may be required)")

    if ( ! missing(facetVar)) facetVar <- jmvcore::resolveQuo(jmvcore::enquo(facetVar))
    if ( ! missing(groupVar)) groupVar <- jmvcore::resolveQuo(jmvcore::enquo(groupVar))
    if ( ! missing(labelVar)) labelVar <- jmvcore::resolveQuo(jmvcore::enquo(labelVar))
    if ( ! missing(sizeVar)) sizeVar <- jmvcore::resolveQuo(jmvcore::enquo(sizeVar))
    if ( ! missing(xvar)) xvar <- jmvcore::resolveQuo(jmvcore::enquo(xvar))
    if ( ! missing(yvar)) yvar <- jmvcore::resolveQuo(jmvcore::enquo(yvar))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(facetVar), facetVar, NULL),
            `if`( ! missing(groupVar), groupVar, NULL),
            `if`( ! missing(labelVar), labelVar, NULL),
            `if`( ! missing(sizeVar), sizeVar, NULL),
            `if`( ! missing(xvar), xvar, NULL),
            `if`( ! missing(yvar), yvar, NULL))

    for (v in facetVar) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in groupVar) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- xyplotbuilderOptions$new(
        annotationsJson = annotationsJson,
        chartSnapshot = chartSnapshot,
        clientBundleHash = clientBundleHash,
        errorBarType = errorBarType,
        exportPath = exportPath,
        exportRequest = exportRequest,
        facetVar = facetVar,
        graphType = graphType,
        groupVar = groupVar,
        labelVar = labelVar,
        paletteLibrary = paletteLibrary,
        showDataPoints = showDataPoints,
        sizeVar = sizeVar,
        styleLibrary = styleLibrary,
        styleStamp = styleStamp,
        summaryFunc = summaryFunc,
        xvar = xvar,
        xyBin = xyBin,
        xyBinCount = xyBinCount,
        xyCILevel = xyCILevel,
        xyDensity2DLevels = xyDensity2DLevels,
        xyEllipseLevel = xyEllipseLevel,
        xyFitType = xyFitType,
        xyLoessSpan = xyLoessSpan,
        xyMarginal = xyMarginal,
        xyMarginalBins = xyMarginalBins,
        xyShowDensity2D = xyShowDensity2D,
        xyStatsCorrType = xyStatsCorrType,
        yvar = yvar,
        chartSpec = chartSpec)

    analysis <- xyplotbuilderClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

